# a dictionary mapping digits with corresponding phone-letters
numeric_to_alpha_dict = {'0': (),
                     '1': (),
                     '2': ('A','B','C'),
                     '3': ('D','E','F'),
                     '4': ('G','H','I'),
                     '5': ('J','K','L'),
                     '6': ('M','N','O'),
                     '7': ('P','Q','R','S'),
                     '8': ('T','U','V'),
                     '9': ('W','X','Y','Z')}

alpha_to_numeric_dict = {'A': ('2'),
                         'B': ('2'),
                         'C': ('2'),
                         'D': ('3'),
                         'E': ('3'),
                         'F': ('3'),
                         'G': ('4'),
                         'H': ('4'),
                         'I': ('4'),
                         'J': ('5'),
                         'K': ('5'),
                         'L': ('5'),
                         'M': ('6'),
                         'N': ('6'),
                         'O': ('6'),
                         'P': ('7'),
                         'Q': ('7'),
                         'R': ('7'),
                         'S': ('7'),
                         'T': ('8'),
                         'U': ('8'),
                         'V': ('8'),
                         'W': ('9'),
                         'X': ('9'),
                         'Y': ('9'),
                         'Z': ('9')}

# for quick searching on 1 letter words, nltk returns many non-useful one-letter words, like the letter 'p'
one_letter_eng_words = ('A', 'I')
# for quick searching 2 letter words, scrabble accepted 2 letter words (107 of them)
two_letter_eng_words = ('AA', 'AB', 'AD', 'AE', 'AG',
                       'AH', 'AI', 'AL', 'AM', 'AR',
                       'AS', 'AT', 'AW', 'AX', 'AY',
                       'BA', 'BE', 'BI', 'BO', 'BY',
                       'DA', 'DE', 'DO',
                       'ED', 'EF', 'EH', 'EL', 'EM',
                       'EN', 'ER', 'ES', 'ET', 'EW',
                       'EX',
                       'FA', 'FE',
                       'GI', 'GO',
                       'HA', 'HE', 'HI', 'HM', 'HO',
                       'ID', 'IF', 'IN', 'IS', 'IT',
                       'JO',
                       'KA', 'KI',
                       'LA', 'LI', 'LO',
                       'MA', 'ME', 'MI', 'MM', 'MO', 'MU', 'MY',
                       'NA', 'NE', 'NO', 'NU',
                       'OO', 'OE', 'OF', 'OH', 'OI',
                       'OK', 'OM', 'ON', 'OP', 'OR',
                       'OS', 'OW', 'OX', 'OY',
                       'PA', 'PE', 'PI', 'PO',
                       'QI',
                       'RE',
                       'SH', 'SI', 'SO',
                       'TA', 'TE', 'TI', 'TO',
                       'UH', 'UM', 'UN', 'UP', 'US',
                       'UT',
                       'WE', 'WO',
                       'VA', 'VI', 'VO',
                       'XI', 'XU',
                       'YA', 'YE', 'YO',
                       'ZA')
